### ISSUE TITLE
Realistic kH/s (or MH/s) - DE0-nano vs. DE2-115 and alt coin compatibility?

### ISSUE THREAD

**Issue by cyanidecotdpnuts** [kramble/FPGA-Litecoin-Miner#8]
I am having a little trouble comparing these two pieces of hardware.
what sort of output can I expect after reaching safe OC settings? and would it be better to go the route of several DE0-nanos as apposed to 1 DE2-115?

Also, as this is compatible with litecoin, would it be easily configurable to mine other alt coins?

**Comment by kramble** [comment]
DE0-Nano 2kHash/sec, DE2-115 rough guess 8kHash/sec (perhaps 16kHash/sec using the newer code).
For even one MH/s you'd need five hundred DE0-Nano boards.

Neither is going to be cost-effective for mining. Even if you could get hold of the boards for zero cost and your electricity and internet is free, its not going to be worth your time in setting these up and mining with them.

I don't recommend mining on any FPGA devices except for novelty, entertainment or educational purposes (and its the latter that brought me into this field, self-education that is).

That said, welcome to the project!
